### ISSUE TITLE
What should be the case of CHP running separately from Hub ?

### ISSUE THREAD

**Issue by SMHari** [globocom/configurable-http-proxy-redis-backend#4]
Hello @jonathansp / team
We are using a CHP proxy running separately from the hub as a separate container in a pod.

If I need to introduce this Redis backend, where this npm package needs to be installed and URI needs to be exported?

**Comment by jonathansp** [comment]
Hi @SMHari 

I've replied [in this thread](https://github.com/jupyterhub/configurable-http-proxy/issues/138#issuecomment-372114172).

**Comment by SMHari** [comment]
Yeah I did checked that @jonathansp 
Thanks for your help :)
